speed_up: 'q'
speed_down: 'z'
linear_speed_up: 'w'
linear_speed_down: 'x'
angular_speed_up: 'e'
angular_speed_down: 'c'
forward: 'i'
forward_right: 'o'
turn_left: 'j'
turn_right: 'l'
forward_left: 'u'
backward: ','
backward_right: '.'
backward_left: 'm'
forward_right_strafe: 'O'
forward_strafe: 'I'
strafe_left: 'J'
strafe_right: 'L'
forward_left_strafe: 'U'
backward_strafe: '<'
backward_right_strafe: '>'
backward_left_strafe: 'M'
up: 't'
down: 'b'