speed_up: 'u'
speed_down: 'j'
linear_speed_up: 'i'
linear_speed_down: 'k'
angular_speed_up: 'o'
angular_speed_down: 'l'
forward: 'w'
forward_right: 'e'
turn_left: 'a'
turn_right: 'd'
forward_left: 'q'
backward: 'x'
backward_right: 'c'
backward_left: 'z'
forward_right_strafe: 'E'
forward_strafe: 'W'
strafe_left: 'A'
strafe_right: 'D'
forward_left_strafe: 'Q'
backward_strafe: 'X'
backward_right_strafe: 'C'
backward_left_strafe: 'Z'
up: 't'
down: 'b'